# Site settings
title: Juan M. Merlos web
email: jmmerlos@merlos.org
description: > # this means to ignore newlines until "baseurl:"
  Personal webpage of Juan Manuel Merlos. 
  <br>I create mobile and web services. 
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://merlos.org" # the base hostname & protocol for your site
twitter_username: merlos
github_username:  merlos

gems:
  - jekyll-redirect-from

# Build settings
markdown: kramdown

permalink: /:categories/:year/:month/:title.html
defaults:
  -
    scope:
      path: _posts/en
    values:
      layout: post
      lang: en
  -
    scope:
      path: _posts/es
    values:
      layout: post
      lang: es
  -
    scope:
      path: _posts/wordpress
    values:
      layout: post
      lang: es
      disqus_comments: false
      hide_index: true
  -
    scope:
      path: _posts/articles
    values:
      layout: post
      lang: es
      disqus_comments: false
      hide_index: true
  -
    scope:
      path: _posts/adianteapps
    values:
      layout: post
      lang: es
      disqus_comments: false
      hide_index: true  
  -
    scope:
      path: _posts/linux
    values:
      layout: post
      lang: es
      disqus_comments: false
      hide_index: true  
