# Site settings
title: merlos.org
email: jmmerlos@merlos.org
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Juan Manuel Merlos. 
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://merlos.org" # the base hostname & protocol for your site
twitter_username: merlos
github_username:  merlos

# Build settings
markdown: kramdown
