# Site settings
title: Juan Manuel Merlos
email: jmmerlos@merlos.org
description: > # this means to ignore newlines until "baseurl:"
  Personal webpage of Juan Manuel Merlos. I create mobile and web services. 
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://merlos.org" # the base hostname & protocol for your site
twitter_username: merlos
github_username:  merlos

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: _posts/en
    values:
      layout: post
      lang: en
  -
    scope:
      path: _posts/es
    values:
      layout: post
      lang: es